### PR TITLE
Fixes and add compatibility with Qt Windows MinGW

### PR DESCRIPTION
**Pull request by bvernoux**

### CODE REVIEW

**Comment by bvernoux** [comment]
> 
> 
>     * Is there a problem with system() on windows? because your fix doesn't work for me and I don't really want to introduce unneeded dependencies to qt.

In fact sytem() work on windows but it open an ugly command windows it is why I have replaced with 
 QProcess::startDetached() which shall work on any platform I will check what is wrong with Linux on my VM with XUbuntu 18.04LTS also it is not a special dependency as it is part of standard Qt libraries since lot of time (already supported in Qt 4.8 ...)

> 
>     * What is the crash symptom with invalid files, is it something like that?
> 
> 
> ```
> terminate called after throwing an instance of 'std::invalid_argument'
>     what():  stold
> Abandon (core dumped)
> ```
I have different crash when testing with my own test files but mainly core dumped ...

> 
>     * OK with other changes.

**Comment by bvernoux** [comment]
Parser fixed QProcess::startDetached issue replaced by QProcess start + waitForFinished() (or timeout 
30s worst case)
I have tested it with success on Windows 7 MinGW64 and XUbuntu 18.04 LTS (64bits) with Qt 5.12.4 but shall work with any Qt version

**Comment by thomaslepoix** [comment]
- Thanks! Yes it's better without this terminal, I'm ok with QProcess but we should add something like this to keep the exit status verification
```
	if(res==false || process_qucs.exitCode()) {
```

- Could you send me your invalid `.sch` file to reproduce the bug ?

**Comment by bvernoux** [comment]
> if(res==false || process_qucs.exitCode()) {

Yes even better with that check

See my test archive with my different tests (some still crash and shall not so there is some issues to fix)
[qucs_microstrip_tests_28Oct2019_bve.zip](https://github.com/thomaslepoix/Qucs-RFlayout/files/3780729/qucs_microstrip_tests_28Oct2019_bve.zip)

**Comment by bvernoux** [comment]
Lats point to be checked later is to replace all C++ cout / cerr output to QDebug or to log them in hidden(or not) debug window as today cout & cerr are not displayed correctly when called from Qt GUI

**Comment by thomaslepoix** [comment]
>Example with strange display (to be checked):
>- TestBandStop_stub_transmission_lines_microstrip.sch

Capture du 2019-10-29 23-30-07

You must use MTEE component instead of a wire intersection because wires are not geometrical objects so RFlayout cannot interpret a pattern like this. Wires should only be used to connect two elements. Plus the orientation of a component (rotation, symetry) matters in its representation. So you must place components like you want those to be.

Your fix prevent the crash but it doesn't solve the problem which is in fact a limitation of the software that is not yet protected by verification.

<br>

>Example with no output/no display (to be checked):
>- filter_bandpass_1GHz.sch
>- TestBandStop_stub_transmission_lines.sch
>- Test_Coplanar_50ohms_FR408_4Layers_OSHPark.sch
>- Test_Coplanar_50ohms_FR408_4Layers_OSHPark_4mm_60mm.sch
>- Test_Coplanar_50ohms_FR408_4Layers_OSHPark_Corrected.sch

CTLIN and TLIN are not things that you can layout on a PCB. The tool support only microstrip elements (except lange coupler because the layout is ambiguous [1]). Coplanar waveguide support is planned but for other components, I don't really see how it could be achieved. They are simply ignored by the parser. In `TestBandStop_stub_transmission_lines.sch` TLINs could be replaced by MLINs.

<br>

>Examples which crash all files with prefix or suffix QucsStudio they are not compatible with qucs 0.0.19+ as QucsStudio is a bit different (mainly header) but it shall not crash to be checked...

The format seems to be the same so the support should be quite trivial. Simple curiosity, does QucsStudio have any advantage over Qucs?

It doesn't really crash, it's an `exit()`. The error and log handling is CLI based and as you said, it is poor with a GUI. I didn't take time yet to review it properly but it is planned too.

<br>

Last thing about equations, variables in components values are neither supported yet [1] so you have to be careful with that.

<br>

[1] : https://sourceforge.net/p/qucs/mailman/message/36768803/

**Comment by bvernoux** [comment]
Thanks for your explanation about TestBandStop_stub_transmission_lines_microstrip.sch and other example not working today
Note: My examples of stub tranmission lines are mainly some export from qucs Filter Synthesis tool and so they do not include MTEE which could be a great improvement if future version of qucs will add that instead of wire.

QucsStudio is much more advanced than qucs in lot of areas for example towards tools like:
- Filter Synthesis (qucsfilter.exe)
- Tranmission Line (qucstransline.exe)
- Device Control  (qucsdev.exe) allow to communicate over GPIB to Spectrum Analyzer and Import them in QucsSTudio

Unfortunately the author does not want to provide any new version after QucsStudio 2.5.7 and code is not available even if based on open source ...

Maybe you can merge those changes and I will push other changes in an other Pull Request ?

**Comment by thomaslepoix** [comment]
I fixed the crash when more than 2 components are on the same net https://github.com/thomaslepoix/Qucs-RFlayout/commit/4e4bf4301b4a74c7c71e04d539fa4c638d9cc825, could you revert this commit https://github.com/thomaslepoix/Qucs-RFlayout/pull/2/commits/215f203983e75e8c4c052f8cbf1817452ca7a7d3 so I can merge?

**Comment by bvernoux** [comment]
Ok done I have removed modifications of commit 215f203983e75e8c4c052f8cbf1817452ca7a7d3

**Comment by thomaslepoix** [comment]
Merged! :)

**Pull request merged**
